# Generated by Django 5.1.7 on 2025-03-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='age',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
