# Generated by Django 5.1.7 on 2025-03-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_trial_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='email',
            field=models.EmailField(default='example@gmil.com', max_length=100),
        ),
    ]
