# Generated by Django 5.1.7 on 2025-03-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_trial_lname_alter_trial_fname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trial',
            name='fname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='trial',
            name='lname',
            field=models.CharField(max_length=50),
        ),
    ]
